# 1. Implement the K-nearest neighbors (KNN) algorithm from scratch. Given a dataset and a query point, classify the query based on the majority label of its k-nearestneighbors.

In [1]:
import math
from collections import Counter

def euclidean_distance(point1, point2):
    distance = 0.0
    for i in range(len(point1)):
        distance += (point1[i] - point2[i]) ** 2
    return math.sqrt(distance)

def knn(dataset, query, k):
    distances = []
    
    for data_point in dataset:
        features = data_point[:-1]  # all columns except the last one (label)
        label = data_point[-1]  # last column is the label
        distance = euclidean_distance(features, query)
        distances.append((distance, label))
    
    distances.sort(key=lambda x: x[0])
    
    k_nearest_labels = [distances[i][1] for i in range(k)]
    
    majority_vote = Counter(k_nearest_labels).most_common(1)[0][0]
    
    return majority_vote

dataset = [
    [2.5, 2.4, 'A'],
    [0.5, 0.7, 'B'],
    [2.2, 2.9, 'A'],
    [1.9, 2.2, 'A'],
    [3.1, 3.0, 'B'],
    [2.3, 2.7, 'A'],
    [1.0, 1.1, 'B'],
    [1.5, 1.6, 'B'],
    [1.1, 0.9, 'B'],
]

query_point = [1.5, 1.5]  
k = 3  

result = knn(dataset, query_point, k)
print(f'The query point {query_point} is classified as: {result}')


The query point [1.5, 1.5] is classified as: B


# 2. Problem: Implement logistic regression in Python. Include training using gradient descent,and calculate class probabilities for binary classification.

In [2]:
import numpy as np

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def compute_cost(X, y, weights):
    m = len(y)
    predictions = sigmoid(np.dot(X, weights))
    cost = -(1/m) * np.sum(y * np.log(predictions) + (1 - y) * np.log(1 - predictions))
    return cost

def gradient_descent(X, y, weights, learning_rate, iterations):
    m = len(y)
    for i in range(iterations):
        predictions = sigmoid(np.dot(X, weights))
        weights -= (learning_rate/m) * np.dot(X.T, (predictions - y))
    return weights

def logistic_regression(X, y, learning_rate, iterations):
    weights = np.zeros(X.shape[1])
    weights = gradient_descent(X, y, weights, learning_rate, iterations)
    return weights

def predict(X, weights):
    probabilities = sigmoid(np.dot(X, weights))
    return [1 if p >= 0.5 else 0 for p in probabilities]

X = np.array([[1, 2], [2, 3], [3, 4], [4, 5], [5, 6]])
y = np.array([0, 0, 0, 1, 1])

X = np.c_[np.ones(X.shape[0]), X]
learning_rate = 0.1
iterations = 1000

weights = logistic_regression(X, y, learning_rate, iterations)
predictions = predict(X, weights)
print("Predictions:", predictions)


Predictions: [0, 0, 0, 1, 1]


# 3. Problem: Write a function to perform matrix multiplication without using external librarieslike NumPy. Multiply two matrices representing weight matrices and input vectors in a neural network layer.

In [3]:
def matrix_multiply(matrix1, matrix2):
    result = [[0 for _ in range(len(matrix2[0]))] for _ in range(len(matrix1))]
    
    for i in range(len(matrix1)):
        for j in range(len(matrix2[0])):
            for k in range(len(matrix2)):
                result[i][j] += matrix1[i][k] * matrix2[k][j]
    
    return result

matrix1 = [
    [1, 2],
    [3, 4],
    [5, 6]
]

matrix2 = [
    [7, 8, 9],
    [10, 11, 12]
]

result = matrix_multiply(matrix1, matrix2)
for row in result:
    print(row)


[27, 30, 33]
[61, 68, 75]
[95, 106, 117]


#  4. Problem: Write a Python function that deep copies a neural network represented as a nested list of layers, where each layer contains weight matrices.

In [4]:
import copy

def deep_copy_neural_network(network):
    return copy.deepcopy(network)

neural_network = [
    [[0.1, 0.2], [0.3, 0.4]],  
    [[0.5, 0.6], [0.7, 0.8]] 
]

copied_network = deep_copy_neural_network(neural_network)

neural_network[0][0][0] = 1.0

print("Original network:", neural_network)
print("Copied network:", copied_network)


Original network: [[[1.0, 0.2], [0.3, 0.4]], [[0.5, 0.6], [0.7, 0.8]]]
Copied network: [[[0.1, 0.2], [0.3, 0.4]], [[0.5, 0.6], [0.7, 0.8]]]


#  5. Problem: Implement a moving average filter for a time series. Given a series of numbers and a window size, return the moving average of the series.

In [5]:
def moving_average(series, window_size):
    moving_averages = []
    for i in range(len(series) - window_size + 1):
        window = series[i:i + window_size]
        window_average = sum(window) / window_size
        moving_averages.append(window_average)
    return moving_averages

# Example usage:
time_series = [10, 20, 30, 40, 50, 60, 70]
window_size = 3

result = moving_average(time_series, window_size)
print(result)

[20.0, 30.0, 40.0, 50.0, 60.0]


# 6. Problem: Write a Python function that applies the ReLU activation function to a list of inputs.

In [6]:
def relu(inputs):
    return [max(0, x) for x in inputs]

# Example usage:
input_values = [-3, -1, 0, 2, 5]

output = relu(input_values)
print(output)


[0, 0, 0, 2, 5]


# 7. Problem: Implement gradient descent to train a linear regression model. Minimize the  mean squared error by adjusting the model weights iteratively.

In [8]:
import numpy as np

def gradient_descent(X, y, learning_rate=0.01, iterations=1000):
    m = len(y)
    theta = np.zeros(X.shape[1])  
    for _ in range(iterations):
        predictions = X.dot(theta)  
        errors = predictions - y  
        gradient = (1/m) * X.T.dot(errors)  
        theta -= learning_rate * gradient   
    return theta

def mean_squared_error(X, y, theta):
    predictions = X.dot(theta)
    error = predictions - y
    mse = (1 / len(y)) * np.dot(error.T, error)
    return mse

# Example usage:
X = np.array([[1, 1], [1, 2], [1, 3], [1, 4]]) 
y = np.array([3, 7, 11, 15])  

learning_rate = 0.01
iterations = 1000

theta = gradient_descent(X, y, learning_rate, iterations)

print("Weights:", theta)

mse = mean_squared_error(X, y, theta)
print("Final Mean Squared Error:", mse)


Weights: [-0.5270054   3.83912416]
Final Mean Squared Error: 0.037364642472698294


# 8. Problem: Write a Python function to perform one-hot encoding of categorical labels for a machine learning task.

In [9]:
import numpy as np

def one_hot_encode(labels):
    unique_labels = sorted(set(labels))  
    label_map = {label: i for i, label in enumerate(unique_labels)}  
    one_hot = np.zeros((len(labels), len(unique_labels)))  
    
    for i, label in enumerate(labels):
        one_hot[i, label_map[label]] = 1  

    return one_hot

labels = ['cat', 'dog', 'fish', 'cat', 'dog']
encoded_labels = one_hot_encode(labels)
print(encoded_labels)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


# 9. Problem: Implement a Python function to calculate the cosine similarity between two vectors, which is often used in text similarity tasks.

In [10]:
import numpy as np

def cosine_similarity(vec1, vec2):
    dot_product = np.dot(vec1, vec2) 
    norm_vec1 = np.linalg.norm(vec1)  
    norm_vec2 = np.linalg.norm(vec2)  
    return dot_product / (norm_vec1 * norm_vec2)  

vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

similarity = cosine_similarity(vector1, vector2)
print(similarity)


0.9746318461970762


# 10. Problem: Given a trained neural network in Python, write a function to prune the network by removing neurons that have small or zero weights.

In [11]:
import numpy as np

def prune_neural_network(network, threshold=0.01):
    pruned_network = []
    
    for layer in network:
        pruned_layer = []
        for weights in layer:
            if np.abs(weights).max() > threshold:
                pruned_layer.append(weights)
        pruned_network.append(pruned_layer)
    
    return pruned_network

neural_network = [
    [np.array([[0.1, 0.0], [0.3, 0.4]]), np.array([[0.0, 0.5], [0.6, 0.0]])],  # First layer
    [np.array([[0.2, 0.0]]), np.array([[0.0, 0.0]])]  # Second layer
]

pruned_network = prune_neural_network(neural_network, threshold=0.01)

for i, layer in enumerate(pruned_network):
    print(f"Layer {i+1}:")
    for weights in layer:
        print(weights)


Layer 1:
[[0.1 0. ]
 [0.3 0.4]]
[[0.  0.5]
 [0.6 0. ]]
Layer 2:
[[0.2 0. ]]


# 11. Problem: Implement a Python function to compute the confusion matrix given true and predicted labels for a classification task.

In [12]:
import numpy as np

def confusion_matrix(y_true, y_pred):
    classes = np.unique(y_true)
    cm = np.zeros((len(classes), len(classes)), dtype=int)  

    for true, pred in zip(y_true, y_pred):
        cm[true, pred] += 1 

    return cm


y_true = np.array([0, 1, 2, 2, 0, 1, 0])  
y_pred = np.array([0, 0, 2, 2, 0, 1, 1])  

cm = confusion_matrix(y_true, y_pred)
print("Confusion Matrix:")
print(cm)


Confusion Matrix:
[[2 1 0]
 [1 1 0]
 [0 0 2]]


# 12. Problem: Write a Python function that performs mini-batch gradient descent for optimizing the weights of a neural network.

In [13]:
import numpy as np

def mini_batch_gradient_descent(X, y, theta, learning_rate=0.01, batch_size=32, iterations=1000):
    m = len(y)
    for _ in range(iterations):
        indices = np.random.permutation(m)
        X_shuffled = X[indices]
        y_shuffled = y[indices]

        for start in range(0, m, batch_size):
            end = start + batch_size
            X_batch = X_shuffled[start:end]
            y_batch = y_shuffled[start:end]

            predictions = X_batch.dot(theta)
            errors = predictions - y_batch
            gradient = (1 / batch_size) * X_batch.T.dot(errors)
            theta -= learning_rate * gradient

    return theta

X = np.array([[1, 1], [1, 2], [1, 3], [1, 4], [1, 5]])
y = np.array([2, 3, 5, 7, 11])
theta = np.zeros(X.shape[1])

learning_rate = 0.01
batch_size = 2
iterations = 1000

optimized_theta = mini_batch_gradient_descent(X, y, theta, learning_rate, batch_size, iterations)
print("Optimized Weights:", optimized_theta)


Optimized Weights: [-0.99858268  2.20068112]


# 13. Problem: Implement k-means clustering from scratch. Given a dataset and the number of clusters k , return the cluster assignments for each data point.

In [14]:
import numpy as np

def k_means(X, k, max_iterations=100):
    m, n = X.shape
    centroids = X[np.random.choice(m, k, replace=False)]
    cluster_assignments = np.zeros(m)
    
    for _ in range(max_iterations):
        distances = np.linalg.norm(X[:, np.newaxis] - centroids, axis=2)
        cluster_assignments = np.argmin(distances, axis=1)

        new_centroids = np.array([X[cluster_assignments == i].mean(axis=0) for i in range(k)])
        
        if np.all(centroids == new_centroids):
            break
        centroids = new_centroids
    
    return cluster_assignments

X = np.array([[1, 2], [1, 4], [1, 0],
              [4, 2], [4, 4], [4, 0]])

k = 2
assignments = k_means(X, k)
print("Cluster Assignments:", assignments)


Cluster Assignments: [1 1 0 1 1 0]


# 14. Problem: Implement a Python function to calculate the softmax of a list of numbers, which is used in multi-class classification problems.

In [15]:
import numpy as np

def softmax(x):
    e_x = np.exp(x - np.max(x))  
    return e_x / e_x.sum(axis=0)

logits = [2.0, 1.0, 0.1]
softmax_values = softmax(np.array(logits))
print("Softmax Values:", softmax_values)


Softmax Values: [0.65900114 0.24243297 0.09856589]


 # 15. Problem: Write a Python function to compute the TF-IDF (Term Frequency-InverseDocument Frequency) for a list of documents.

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer

def compute_tfidf(documents):
    vectorizer = TfidfVectorizer()
    tfidf_matrix = vectorizer.fit_transform(documents)
    return tfidf_matrix.toarray(), vectorizer.get_feature_names_out()

documents = [
    "the cat sat on the mat",
    "the dog sat on the log",
    "the cat and the dog are friends"
]

tfidf_values, feature_names = compute_tfidf(documents)
print("Feature Names:", feature_names)
print("TF-IDF Matrix:\n", tfidf_values)


Feature Names: ['and' 'are' 'cat' 'dog' 'friends' 'log' 'mat' 'on' 'sat' 'the']
TF-IDF Matrix:
 [[0.         0.         0.37420726 0.         0.         0.
  0.49203758 0.37420726 0.37420726 0.58121064]
 [0.         0.         0.         0.37420726 0.         0.49203758
  0.         0.37420726 0.37420726 0.58121064]
 [0.42439575 0.42439575 0.32276391 0.32276391 0.42439575 0.
  0.         0.         0.         0.50130994]]


# 16. Problem: Implement an algorithm to find the principal components of a dataset usingsingular value decomposition (SVD), which is a core part of PCA (Principal Component Analysis)

In [17]:
import numpy as np

def pca_svd(X, n_components):
    X_meaned = X - np.mean(X, axis=0)
    U, S, Vt = np.linalg.svd(X_meaned, full_matrices=False)
    return U[:, :n_components], S[:n_components], Vt[:n_components, :]

X = np.array([[2.5, 2.4], [0.5, 0.7], [2.2, 2.9], [1.9, 2.2], [3.1, 3.0], [2.3, 2.7], [2, 1.6], [1, 1.1], [1.5, 1.6], [1.1, 0.9]])
n_components = 1

principal_components, singular_values, explained_variance = pca_svd(X, n_components)
print("Principal Components:\n", principal_components)
print("Singular Values:\n", singular_values)


Principal Components:
 [[-0.24356016]
 [ 0.52290258]
 [-0.29187014]
 [-0.08066321]
 [-0.49296275]
 [-0.26855801]
 [ 0.02915456]
 [ 0.3366935 ]
 [ 0.128858  ]
 [ 0.36000563]]
Singular Values:
 [3.3994484]


# 17. Problem: Write a Python function to calculate the AUC-ROC score for a binary classification problem, given the true labels and predicted probabilities.

In [18]:
from sklearn.metrics import roc_auc_score

def calculate_auc_roc(y_true, y_scores):
    return roc_auc_score(y_true, y_scores)

y_true = [0, 0, 1, 1]
y_scores = [0.1, 0.4, 0.35, 0.8]

auc_roc = calculate_auc_roc(y_true, y_scores)
print("AUC-ROC Score:", auc_roc)


AUC-ROC Score: 0.75


# 18. Problem: Implement a Python function to apply dropout regularization to the neurons of agiven neural network during training.

In [19]:
import numpy as np

def apply_dropout(layer_output, dropout_rate):
    if dropout_rate < 0 or dropout_rate >= 1:
        raise ValueError("Dropout rate must be between 0 and 1.")
    keep_prob = 1 - dropout_rate
    mask = np.random.binomial(1, keep_prob, size=layer_output.shape)
    return layer_output * mask / keep_prob

layer_output = np.array([[0.5, 0.6], [0.2, 0.3], [0.8, 0.7]])
dropout_rate = 0.5

output_with_dropout = apply_dropout(layer_output, dropout_rate)
print("Output with Dropout:\n", output_with_dropout)


Output with Dropout:
 [[0. 0.]
 [0. 0.]
 [0. 0.]]


 # 19. Problem: Write a Python function to perform feature scaling using standardization (z-score normalization), which transforms features to have a mean of 0 and a standard deviation of 1.

In [20]:
import numpy as np

def standardize_features(X):
    mean = np.mean(X, axis=0)
    std = np.std(X, axis=0)
    standardized_X = (X - mean) / std
    return standardized_X

X = np.array([[1, 2], [3, 4], [5, 6]])
standardized_X = standardize_features(X)
print("Standardized Features:\n", standardized_X)


Standardized Features:
 [[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]
